### ISSUE TITLE
API communication doesn't work

### ISSUE THREAD

**Issue by mwkm00** [JanSkn/poker-calculator#6]
**Describe the bug**
After setting up the project according to the instructions, moving the cards to the table or to the hand results in API error "422 Unprocessable Entity"

**To Reproduce**
1. Set up the project
2. Run the app using uvicorn
3. Move the card

**Expected behavior**
Normal odds calculation

**Desktop**
 - uvicorn: Running uvicorn 0.23.2 with CPython 3.10.9 on Darwin
 - Python: 3.10.9
 - FastAPI: 0.103.1
 - python-multipart: 0.0.6 (?)

**Additional context**
It seems that Pydantic interpretation of JSON body is at fault: currently, the API expects a list, changing the functions in api.py to "cards: list[list]" seems to fix the issue

Payload to update_hand_cards:
```
[["Hearts", "7"]]
```

Response to current payload after moving a card:
```
{
    "detail": [
        {
            "type": "missing",
            "loc": [
                "body",
                "cards"
            ],
            "msg": "Field required",
            "input": null,
            "url": "https://errors.pydantic.dev/2.3/v/missing"
        }
    ]
}
```

**Comment by JanSkn** [comment]
Hello, thank you very much for the issue. That's strange, I don't get any error, could you give me some more detail or send a screenshot?

**Comment by mwkm00** [comment]
Sure! Here you go:
<img width="1664" alt="Screenshot 2023-09-16 at 16 05 11" src="https://github.com/JanSkn/poker-calculator/assets/97192632/56c2a847-4b30-4cae-8e9c-f91f535710be">
<img width="1664" alt="Screenshot 2023-09-16 at 16 05 01" src="https://github.com/JanSkn/poker-calculator/assets/97192632/bd247b87-3bcc-4136-846c-71c555d3598e">
<img width="1664" alt="Screenshot 2023-09-16 at 16 04 31" src="https://github.com/JanSkn/poker-calculator/assets/97192632/d7df5e12-fd8a-487a-91a5-fea1a5b16636">
<img width="655" alt="Screenshot 2023-09-16 at 16 05 35" src="https://github.com/JanSkn/poker-calculator/assets/97192632/1dc78c7d-dc8d-4e7b-a343-38b98de9c76f">

**Comment by mwkm00** [comment]
I should also add that I'm running the app on clear Python venv. The screenshots are from macOS, but I just tried it on Windows and it doesn't seem to work either. When setting up the project and starting the app for the first time I get this error:
```
...
    raise RuntimeError(multipart_not_installed_error) from None
RuntimeError: Form data requires "python-multipart" to be installed.

pip install python-multipart
```
After installing python-multipart (v 0.0.6), it works like shown in the screenshots above.

**Comment by JanSkn** [comment]
Thank you! I indeed forgot that I had to install python-multipart. And with your changes, it should work now.
